name: benchmark 

channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.6
  - openjdk==8.0.152
  - pyspark==2.3.2
  - papermill==0.14.2
  - psutil==5.4.8
  - watermark==1.6.1
  - pip
  - pip:
      - msgpack==0.5.6
      - mmtfPyspark==0.3.5

