name: benchmark 
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - biopython==1.72 
  - matplotlib==3.0.2
  - numpy==1.15.4
  - openjdk==8.0.152
  - papermill==0.14.2
  - pyarrow==0.11.1
  - psutil==5.4.8
  - watermark==1.6.1
  - pip
  - pip:
      - git+https://github.com/sbl-sdsc/mmtf-pyspark.git#egg=mmtf-pyspark[complete] 
